salesforce-ticketing-system/ticketing-system/force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <label>Role</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>RName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-ticketing-system/ticketing-system/force-app/main/default/objects/Role__c/fields/Role_Name__c.field-meta.xml
<CustomField>
    <fullName>Role_Name__c</fullName>
    <label>Role Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-ticketing-system/ticketing-system/force-app/main/default/classes/RoleController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-11-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class RoleController {
    @AuraEnabled(cacheable=true)
    public static List<Role__c> getRoles() {
        return [SELECT Id, Role_Name__c FROM Role__c WHERE Role_Name__c NOT IN ('Admin', 'User')];
    }
}